global_frame: odom
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  - {name: obstacles_camera,          type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  

# obstacles_camera:
#     enabled: true
#     voxel_decay: 1.5
#     decay_model: -1
#     voxel_size: 0.1
#     track_unknown_space: true
#     max_obstacle_height: 1.3
#     unknown_threshold: 15
#     mark_threshold: 0
#     update_footprint_enabled: true
#     combination_method: 1
#     origin_z: 0.0
#     publish_voxel_map: true 
#     transform_tolerance: 0.2   
#     mapping_mode: false 
#     map_save_duration: 60
#     observation_source: camera