footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

# plugins:
#   - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
#   - {name: obstacles_camera,          type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
#   - {name: inflation,                 type: "costmap_2d::InflationLayer"}

obstacles_camera:
    enabled: true
    voxel_decay: 1.5
    decay_model: -1
    voxel_size: 0.1
    track_unknown_space: true
    max_obstacle_height: 3.0
    unknown_threshold: 15
    mark_threshold: 0
    update_footprint_enabled: true
    combination_method: 1
    origin_z: 0.0
    publish_voxel_map: true
    transform_tolerance: 0.2
    mapping_mode: false
    map_save_duration: 60
    min_obstacle_height: 0.1
    observation_source: camera_clear camera_mark  
    camera_mark:    
        data_type: PointCloud2
        topic: realsense/depth/color/points
        marking: true
        clearing: false
        min_obstacle_height: 0.3     #default 0, meters
        max_obstacle_height: 3.0     #defaule 3, meters
        expected_update_rate: 0.0    #default 0, if not updating at this rate at least, remove from buffer
        observation_persistence: 0.0 #default 0, use all measurements taken during now-value, 0=latest 
        inf_is_valid: false          #default false, for laser scans
        clear_after_reading: true    #default false, clear the buffer after the layer gets readings from it
        filter: "voxel"              #default passthrough, apply "voxel", "passthrough", or no filter to sensor data, recommended to have at one filter on
        voxel_min_points: 0          #default 0, minimum points per voxel for voxel filter
    camera_clear:
        enabled: true                #default true, can be toggled on/off with associated service call
        data_type: PointCloud2
        topic: realsense/depth/color/points
        marking: false
        clearing: true
        min_z: 0.1                   #default 0, meters
        max_z: 7.0                   #default 10, meters
        vertical_fov_angle: 0.7      #default 0.7, radians
        horizontal_fov_angle: 1.04   #default 1.04, radians
        decay_acceleration: 1.       #default 0, 1/s^2. If laser scanner MUST be 0
        model_type: 0                #default 0 (depth camera). Use 1 for 3D Lidar


obstacles_laser: 
    observation_source: laser
    laser: 
        {data_type: LaserScan,
            clearing: true,
            marking: true,
            topic: scan,
            inf_is_valid: true}

inflation:
    inflation_radius: 1.5