  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: true
  rolling_window: false
  resolution: 0.05
  static_layer:
    map_topic: map
    subscribe_to_updates: true
    lethal_cost_threshold: 80
  inflater_layer:
    inflation_radius: 1.00
    cost_scaling_factor: 1.5

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}