  # update_frequency: 10.0
  # publish_frequency: 10.0
  static_map: true
  rolling_window: false
  resolution: 0.05
  static_layer:
    map_topic: map
    subscribe_to_updates: true
    lethal_cost_threshold: 255
  inflater_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 1.0
  lane_layer:
    enabled: true
    map_topic: lane_map
    subscribe_to_updates: false
    trinary_costmap: false
    lethal_cost_threshold: 255

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
  - {name: voxel_layer2, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  # - {name: lane_layer, type: "costmap_2d::StaticLayer"}