  odom_topic: odom
  map_frame: map
    
 # Trajectory
  
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.03
  global_plan_overwrite_orientation: False
  max_global_plan_lookahead_dist: 6.0
  feasibility_check_no_poses: 5
  force_reinit_new_goal_angular: 0.36
  force_reinit_new_goal_dist: 0.4
  no_reverse: False
  allow_init_with_backwards_motion: False
    
 # Robot
         
  max_vel_x: 1.0
  max_vel_x_backwards: 0.04
  max_vel_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_theta: 0.4 
  min_turning_radius: 0.0
  footprint_model:
    type: "polygon"
    # vertices: [[-0.5, -0.30], [-0.5, 0.30], [0.5, 0.30], [0.5, -0.30]] #HUSKY FOOTPRINT
    vertices: [[-0.3, -0.18], [-0.3, 0.18], [0.2, 0.18], [0.2, -0.18]] #PIONEER FOOTPRINT

 # GoalTolerance
    
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  free_goal_vel: False
    
 # Obstacles
    
  min_obstacle_dist: 0.9
  inflation_dist: 1.0
  include_costmap_obstacles: True
  include_dynamic_obstacles: True
  costmap_obstacles_behind_robot_dist: 0.5
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 10

 # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.02
  weight_max_vel_x: 50.0
  weight_max_vel_y: 0.0
  weight_max_vel_theta: 500.0
  weight_acc_lim_x: 500.0
  weight_acc_lim_y: 0.0
  weight_acc_lim_theta: 560.0
  weight_kinematics_nh: 10000.0
  weight_kinematics_forward_drive: 1000.0
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 10
  weight_inflation: 5.5
  weight_obstacle: 100.0
  weight_dynamic_obstacle: 0.0
  weight_dynamic_obstacle_inflation: 0.0
  weight_viapoint: 600.0


 # Homotopy Class Planner

  enable_homotopy_class_planning: False
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 1
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 2
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45


  # shutdown_costmaps: false
  # controller_frequency: 10.0
  # planner_patience: 5.0
  # controller_patience: 15.0
  # conservative_reset_dist: 3.0
  # planner_frequency: 5.0
  # oscillation_timeout: 10.0
  # oscillation_distance: 0.2
  #ViaPoints
  global_plan_viapoint_sep: 1.3